"""
builder.java
============

Generates plain, dependency-free Java constant classes so the Paper
plugin never hardcodes a resource identifier. Every class here is pure
data -- string constants -- and contains zero gameplay logic, matching
the hard boundary between this asset pipeline and the plugin.

Generated classes:
    CorovaModels.java           model identifiers, per item
    CorovaCustomModelData.java  custom_model_data selector strings
    CorovaBaseItems.java        vanilla base item each custom item rides on
    CorovaSounds.java           sound event identifiers
"""

from __future__ import annotations

from . import util
from .config import NAMESPACE, Paths
from .registry import ItemAsset, Registry

_PACKAGE = "net.corova.chronicles.generated"

_HEADER = (
    "// -----------------------------------------------------------------\n"
    "// AUTO-GENERATED by CorovaAssets. Do not edit by hand.\n"
    "// Regenerate with: python build.py\n"
    "// -----------------------------------------------------------------\n"
)


def _string_constant(name: str, value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'    public static final String {name} = "{escaped}";'


class JavaGenerator:
    def __init__(self, paths: Paths, logger) -> None:
        self.paths = paths
        self.logger = logger

    def generate(self, registry: Registry) -> int:
        written = 0
        written += self._write_class(
            "CorovaModels",
            "Resource-location of each generated item model.",
            [(item.java_constant, item.model_id) for item in registry.items],
        )
        written += self._write_class(
            "CorovaCustomModelData",
            "custom_model_data selector string for each item's minecraft:select case.",
            [(item.java_constant, item.custom_model_data) for item in registry.items],
        )
        written += self._write_class(
            "CorovaBaseItems",
            "The vanilla item each custom item is attached to.",
            [(item.java_constant, item.base_item) for item in registry.items],
        )

        if registry.sounds:
            written += self._write_class(
                "CorovaSounds",
                "Sound event identifiers available in this pack.",
                [
                    (util.to_screaming_snake_case(sound.event_name.replace(".", "_")), f"{NAMESPACE}:{sound.event_name}")
                    for sound in registry.sounds
                ],
            )

        self.logger.info(f"{written} Java helper class(es) generated")
        return written

    def _write_class(self, class_name: str, doc: str, constants: list[tuple[str, str]]) -> int:
        if not constants:
            return 0

        # Guard against duplicate constant names (e.g. two categories
        # normalizing to the same identifier) by keeping first-seen only
        # and warning about the collision instead of emitting invalid Java.
        seen: dict[str, str] = {}
        for const_name, value in constants:
            if const_name in seen and seen[const_name] != value:
                self.logger.warn(
                    f"duplicate Java constant name '{const_name}' in {class_name} -- keeping first value"
                )
                continue
            seen[const_name] = value

        lines = [_HEADER, f"package {_PACKAGE};", "", "/**", f" * {doc}", " */",
                 f"public final class {class_name} {{", "", f"    private {class_name}() {{}}", ""]
        for const_name, value in seen.items():
            lines.append(_string_constant(const_name, value))
        lines.append("")
        lines.append("}")
        lines.append("")

        dest = self.paths.java_dir / f"{class_name}.java"
        util.ensure_dir(dest.parent)
        dest.write_text("\n".join(lines), encoding="utf-8")
        return 1
